[project]
name = "no-read"
version = "0.1.0"
description = "sync weread infomation to Notion"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiolimiter>=1.2.1",
    "httpx>=0.28.0",
    "notion-client>=2.4.0",
]
