name: Sync WeChat Reading to Notion

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  push:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - 'main.py'
      - 'config.py'
      - '.github/workflows/sync.yml'

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || pip install -e .
        
    - name: Create logs directory
      run: mkdir -p logs
      
    - name: Inject configuration from environment variables
      run: |
        python scripts/inject_config.py
      env:
        WEREAD_COOKIE: ${{ secrets.WEREAD_COOKIE }}
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        NOTION_PARENT_PAGE_ID: ${{ secrets.NOTION_PARENT_PAGE_ID }}
        SYNC_ALL_BOOKS: ${{ vars.SYNC_ALL_BOOKS }}
        SYNC_FINISHED_BOOKS: ${{ vars.SYNC_FINISHED_BOOKS }}
        SYNC_UNFINISHED_BOOKS: ${{ vars.SYNC_UNFINISHED_BOOKS }}
        SYNC_BOOK_COVERS: ${{ vars.SYNC_BOOK_COVERS }}
        SYNC_BOOK_REVIEWS: ${{ vars.SYNC_BOOK_REVIEWS }}
        SYNC_READING_NOTES: ${{ vars.SYNC_READING_NOTES }}
        BATCH_SIZE: ${{ vars.BATCH_SIZE }}
        BATCH_DELAY: ${{ vars.BATCH_DELAY }}
        WEREAD_RATE_LIMIT: ${{ vars.WEREAD_RATE_LIMIT }}
        WEREAD_REQUEST_DELAY: ${{ vars.WEREAD_REQUEST_DELAY }}
        NOTION_RATE_LIMIT: ${{ vars.NOTION_RATE_LIMIT }}
        NOTION_REQUEST_TIMEOUT: ${{ vars.NOTION_REQUEST_TIMEOUT }}
        LOG_LEVEL: ${{ vars.LOG_LEVEL }}
        MIN_NOTE_LENGTH: ${{ vars.MIN_NOTE_LENGTH }}
        EXCLUDE_PRIVATE_NOTES: ${{ vars.EXCLUDE_PRIVATE_NOTES }}
        EXCLUDE_EMPTY_BOOKS: ${{ vars.EXCLUDE_EMPTY_BOOKS }}
        MAX_RETRIES: ${{ vars.MAX_RETRIES }}
        RETRY_DELAY: ${{ vars.RETRY_DELAY }}
        ENABLE_CACHE: ${{ vars.ENABLE_CACHE }}
        CACHE_EXPIRE_TIME: ${{ vars.CACHE_EXPIRE_TIME }}
        
    - name: Run sync
      run: |
        python main.py
      env:
        WEREAD_COOKIE: ${{ secrets.WEREAD_COOKIE }}
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        NOTION_PARENT_PAGE_ID: ${{ secrets.NOTION_PARENT_PAGE_ID }}
        
    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: sync-logs
        path: logs/
        retention-days: 7